def generate(data):
    raise Exception('deliberately broken generate function')
