def generate(_data):
    raise Exception("deliberately broken generate function")
